---
version: '3'
services:
  zipkin-cassandra:
    image: openzipkin/zipkin-cassandra:2.11
    hostname: zipkin-cassandra
    ports:
      - 9042:9042
  zipkin:
    image: openzipkin/zipkin:2.11
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      STORAGE_TYPE: cassandra3
      CASSANDRA_CONTACT_POINTS: zipkin-cassandra
    ports:
      - 9411:9411
    depends_on:
      - kafka
  zipkin-ui:
    image: openzipkin/zipkin-ui:2.11
    environment:
      ZIPKIN_BASE_URL: http://zipkin:9411
    ports:
      - 8080:80
  zipkin-dependency-streaming:
    image: syscomiddleware/zipkin-dependencies-streaming:0.1.4
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      STORAGE_TYPE: CASSANDRA
      CASSANDRA_CONTACT_POINTS: zipkin-cassandra
      CASSANDRA_KEYSPACE: zipkin2
    depends_on:
      - zipkin
      - zipkin-cassandra
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper
  schema-registry:
    image: confluentinc/cp-schema-registry:5.0.0
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
    depends_on:
      - kafka

