---
version: '3'
services:
  hello-service:
    image: hello-service
    ports:
      - 18000:18000
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TRANSLATION_SERVICE_BASE_URL=http://hello-translation:18010
      - ZIPKIN_API_ENDPOINT=http://pitchfork:8080/api/v2/spans
  hello-client:
    image: hello-client
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - HELLO_SERVICE_BASE_URL=http://hello-service:18000
      - ZIPKIN_API_ENDPOINT=http://pitchfork:8080/api/v2/spans
  hello-translation:
    image: hello-translation
    ports:
      - 18010:18010
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ZIPKIN_API_ENDPOINT=http://pitchfork:8080/api/v2/spans
  hello-consumer:
    image: hello-consumer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ZIPKIN_API_ENDPOINT=http://pitchfork:8080/api/v2/spans
