---
version: '3'
services:
  twitter-stream-processor:
    image: twitter-stream-processor
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
  twitter-console-consumer:
    image: twitter-console-consumer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
